import Head from "next/head";

import { NextPageWithLayout } from "../_app";
import Layout from "@/features/dashboard/layout";
import { ReactElement } from "react";
import ChatCanvas from "@/features/dashboard/components/chat-canvas";
const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Animai | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ChatCanvas />
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
